### ISSUE TITLE
need help about this issue/error when installed json decoder

### ISSUE THREAD

**Issue by xauth000** [carstein/burp-extensions#8]
hello good morning
i am using jython 2.7.1 and java jdk 8.
burp 1.7.36 community edition.When i installed json decoder it installed successfully but not loaded in burp .i noticed in the burp Extensions windows as it is showing unchecked.When i tried to make it check.it throwed this error.
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.python.core.io.BufferedReader.clear(BufferedReader.java:147)
	at org.python.core.io.BufferedReader.<init>(BufferedReader.java:27)
	at org.python.core.PyFile.createBuffer(PyFile.java:227)
	at org.python.core.PyFile.file___init__(PyFile.java:185)
	at org.python.core.PyFile.file___init__(PyFile.java:178)
	at org.python.core.PyFile.<init>(PyFile.java:101)
	at org.python.core.PySystemState.<init>(PySystemState.java:237)
	at org.python.core.PySystemState.doInitialize(PySystemState.java:1112)
	at org.python.core.PySystemState.initialize(PySystemState.java:1023)
	at org.python.core.PySystemState.initialize(PySystemState.java:979)
	at org.python.core.PySystemState.initialize(PySystemState.java:974)
	at org.python.core.PySystemState.initialize(PySystemState.java:969)
	at org.python.core.PySystemState.initialize(PySystemState.java:965)
	at org.python.core.ThreadStateMapping.getThreadState(ThreadStateMapping.java:56)
	at org.python.core.Py.getThreadState(Py.java:1668)
	at org.python.core.Py.getThreadState(Py.java:1664)
	at org.python.core.Py.getSystemState(Py.java:1684)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:105)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at burp.ohg.<init>(Unknown Source)
	at burp.spf.a(Unknown Source)
	at burp.khc.a(Unknown Source)
	at burp.khc.a(Unknown Source)
	at burp.vkb.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
how can  sort out this issue.Thanks in Advance

**Comment by xauth000** [comment]
@carstein looking forward your reply

**Comment by carstein** [comment]
I haven't tested this particular setup, but it does look like some sort of incompatibility between jython and Java. Can you try with jdk9?

**Comment by xauth000** [comment]
@carstein yea i changed to jdk9 and i got this error

ImportError: Cannot import site module and its dependencies: No module named site
Determine if the following attributes are correct:
  * sys.path: [/usr/share/java/Lib, __classpath__, __pyclasspath__/]
    This attribute might be including the wrong directories, such as from CPython
  * sys.prefix: /usr/share/java
    This attribute is set by the system property python.home, although it can
    be often automatically determined by the location of the Jython jar file

You can use the -S option or python.import.site=false to not import the site module

	at org.python.core.Py.ImportError(Py.java:334)
	at org.python.core.Py.importSiteIfSelected(Py.java:1803)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:116)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at burp.ohg.<init>(Unknown Source)
	at burp.spf.a(Unknown Source)
	at burp.gih.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)
